import type { BackendEnvironment } from './execution/backend-config.mts';
export function executionEnvironment():BackendEnvironment {
 const {EXECUTION_REGISTRY,EXECUTION_RUNNER_URL,EXECUTION_RUNNER_AUDIENCE,EXECUTION_CHECKPOINT_AUDIENCE,EXECUTION_CONTROL_KEY,EXECUTION_RUNNER_KEY,EXECUTION_EVIDENCE_KEY}=process.env;
 return {EXECUTION_REGISTRY,EXECUTION_RUNNER_URL,EXECUTION_RUNNER_AUDIENCE,EXECUTION_CHECKPOINT_AUDIENCE,EXECUTION_CONTROL_KEY,EXECUTION_RUNNER_KEY,EXECUTION_EVIDENCE_KEY};
}
