import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {localFixture} from '../local/fixture.mjs';
import {launchRestrictedBrowser} from '../browser/network.mjs';
import {claimWorkspaceRun} from '../../lib/workspace-runs/service.mts';
const {chromium}=await import(process.env.EXECUTION_PLAYWRIGHT_MODULE?pathToFileURL(resolve(process.env.EXECUTION_PLAYWRIGHT_MODULE)).href:new URL('../browser/node_modules/playwright/index.mjs',import.meta.url).href);
const f=await localFixture();let restricted;
try {
 const owner=f.alice.userId,now=Date.now();
 await f.db.prepare('INSERT INTO workspace_projects VALUES(?,?,?,?)').bind('browser-project',owner,'Browser test',now).run();
 await f.db.prepare("INSERT INTO workspace_connections(id,owner,project_id,name,workspace,version,capabilities,token_hash,token_expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind('browser-connection',owner,'browser-project','Synthetic workspace','synthetic-repo','1','["execute"]','synthetic',now+86400000,now).run();
 for(const id of ['ticket-a','ticket-b'])await f.db.prepare("INSERT INTO records VALUES(?,?,'ticket',?,1,?,?)").bind(id,owner,JSON.stringify({title:'Browser '+id,project:'Browser test',status:'todo'}),new Date(now).toISOString(),new Date(now).toISOString()).run();
 restricted=await launchRestrictedBrowser(chromium,[f.origin]);const {context}=restricted,page=await context.newPage(),writes=[];
 page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/api/workspace-runs'))writes.push(request.postDataJSON());});
 const login=await context.request.post(f.origin+'/api/auth/login',{headers:{origin:f.origin},data:{username:'alice',password:'synthetic-password'}});assert.equal(login.status(),200);
 await page.goto(f.origin);await page.getByRole('button',{name:/Ticket 看板/}).click();
 const panel=page.locator('section[aria-label="本机 Agent 开发执行"]');

 await panel.getByLabel('开发 Ticket',{exact:true}).selectOption('ticket-a');
 await panel.getByLabel('执行期限（分钟）',{exact:true}).fill('17');
 await panel.getByRole('button',{name:'申请开发执行',exact:true}).waitFor({state:'visible'});
 await f.db.prepare("UPDATE records SET revision=2 WHERE id='ticket-a'").run();
 await panel.getByRole('button',{name:'申请开发执行',exact:true}).click();
 await panel.getByText('关联数据已刷新，输入已保留。请刷新 Ticket 并确认修订后重试。').waitFor();
 assert.equal(await panel.getByLabel('执行期限（分钟）',{exact:true}).inputValue(),'17');
 assert.equal((await f.db.prepare('SELECT count(*) AS n FROM workspace_runs').first()).n,0);
 assert.equal(writes[0].ticketId,'ticket-a');assert.equal(writes[0].revision,1);
 await page.getByRole('button',{name:'刷新数据',exact:true}).click();
 await panel.getByText('选中的 Ticket 已消失、移出项目或修订已改变，请明确重新选择。').waitFor();
 assert.equal(await panel.getByRole('button',{name:'申请开发执行',exact:true}).count(),0);
 await panel.getByRole('button',{name:'重新选择 Ticket',exact:true}).click();
 await panel.getByLabel('开发 Ticket',{exact:true}).selectOption('ticket-a');
 await panel.getByLabel('执行期限（分钟）',{exact:true}).fill('17');
 await panel.getByRole('button',{name:'申请开发执行',exact:true}).click();
 await panel.getByRole('button',{name:'批准开发',exact:true}).waitFor();
 assert.equal(writes[1].ticketId,'ticket-a');assert.equal(writes[1].revision,2);
 const held=await f.db.prepare('SELECT id,state,timeout_ms FROM workspace_runs WHERE ticket_id=?').bind('ticket-a').first();
 assert.equal(held.state,'pending');assert.equal(held.timeout_ms,17*60000);
 const principal={id:'browser-connection',owner,projectId:'browser-project',project:'Browser test',capabilities:['execute']};
 assert.equal((await claimWorkspaceRun(f.db,principal)).job,null);
 // Current pending Run is older than 101 synthetic immutable history rows.
 for(let i=0;i<101;i++)await f.db.prepare("INSERT INTO workspace_runs(id,owner,ticket_id,ticket_revision,ticket_body,connection_id,project_id,project,workspace,request_id,input_key,timeout_ms,state,created_at,updated_at) SELECT ?,owner,ticket_id,1,ticket_body,connection_id,project_id,project,workspace,?,input_key,timeout_ms,'cancelled',?,? FROM workspace_runs WHERE id=?").bind('historical-'+i,'historical-'+i,now+10000+i,now+10000+i,held.id).run();
 await panel.getByRole('button',{name:'刷新执行',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('[data-run-id]').length===102);
 assert.equal(await panel.getByRole('button',{name:'批准开发',exact:true}).count(),1);
 assert.equal(await panel.getByRole('button',{name:'申请开发执行',exact:true}).count(),0);
 assert.equal(await panel.getByText('历史修订 · Ticket v1',{exact:true}).count(),101);
 assert.equal(writes.length,2,'pagination/refresh never writes');
 mkdirSync('test-results/ticket-execution',{recursive:true});await panel.screenshot({path:'test-results/ticket-execution/current-and-history.png'});
 await page.evaluate(()=>{sessionStorage.setItem('execution-request:synthetic','private-input');sessionStorage.setItem('execution-decision:synthetic','private-decision');});
 const logout=await context.request.post(f.origin+'/api/auth/logout',{headers:{origin:f.origin},data:{}});assert.equal(logout.status(),200);
 await panel.getByRole('button',{name:'刷新执行',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('[data-run-id]').length===0);
 assert.ok(!(await page.locator('body').innerText()).includes('Browser ticket-a'));
 assert.equal(await page.locator('[data-run-id]').count(),0);
 assert.deepEqual(await page.evaluate(()=>[sessionStorage.getItem('execution-request:synthetic'),sessionStorage.getItem('execution-decision:synthetic')]),[null,null]);
 assert.deepEqual(restricted.requestedExternal,[]);
 console.log('PASS real Chromium: exact revision, 409 input retention, explicit reselection, pending not claimable, 102-row pagination and logout clearing');
}finally{await restricted?.close();await f.close();}
